defaults:
  - default
_target_: models.qwen.Qwen25
model_name: qwen25
probe_layers: {
  'early_mlp': ['model', 'layers', '2'],
  'intermediate_mlp': ['model', 'layers', '12'],
  'late_mlp': ['model', 'layers', '27'],
}