_target_: pytorch_lightning.trainer.Trainer
default_root_dir: ${paths.output_dir}
min_epochs: 1 # prevents early stopping
max_epochs: 100
accelerator: gpu
devices: 1
check_val_every_n_epoch: 1 # perform a validation loop every N training epochs
deterministic: True 
accumulate_grad_batches: 1
num_sanity_val_steps: 0  # set to 0 to skip sanity check
fast_dev_run: False  # set to True to quickly run a batch of train, val, test for debugging