task_name: search
model_name: qwen
n_objects: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
n_trials: 100
size: 40
colors: [red, blue, green, yellow, purple]
shapes: ['triangle', 'heart', 'star', 'circle', 'square']
shape_inds: [9, 96, 98, 100, 101]
canvas_size: [512, 512]
