task_name: search
model_name: qwen
min_objects: 4
max_objects: 16
n_trials: 100
size: 40
colors:
  - red
  - blue
  - green
  - yellow
shapes:
  - circle
  - square
  - triangle
shape_inds:
  - 0
  - 1
  - 2
canvas_size: [512, 512]
