task_name: search
model_name: qwen
min_objects: 4
max_objects: 16
n_trials: 100
size: 40
colors:
  - red
  - blue
  - green
  - yellow
shapes:
  - circle
  - square
  - triangle
  - cross
  - pentagon
  - hexagon
  - star
  - heart
shape_inds:
  - 0  # circle
  - 1  # square  
  - 2  # triangle
  - 3  # cross
  - 4  # pentagon
  - 5  # hexagon
  - 6  # star
  - 7  # heart
canvas_size: [512, 512]
