task_name: search
model_name: qwen
min_objects: 4
max_objects: 16
n_trials: 100
size: 40
colors: [red, blue, green, yellow, purple]
shapes: ['triangle', 'heart', 'star', 'circle', 'square']
shape_inds: [9, 96, 98, 100, 101]
canvas_size: [512, 512]
