# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}"
  name: "${dataset.task_name}"
  version: "tensorboard"
  log_graph: False
  default_hp_metric: True
  prefix: ""
  flush_secs: 30
