# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: loggers.logger.MetricsLogger #lightning.pytorch.loggers.TensorBoardLogger #lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/${dataset.task_name}/${dataset.model_name}/${probe.probe_name}/${dataset.layer_name}/"
  name: 'logs'
  version: null
  log_graph: False
  prefix: ''
